server:
  port: 9002

spring:
  application:
    name: COMMON-SERVICE


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    hostname: localhost

findany:
  jwt:
    secret: mytown
