server:
  port: 8080
  servlet:
    context-path: /find-any
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
spring:
  application:
    name: API-GATEWAY

eureka:
  client:
    registry-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    hostname: localhost

findany:
  jwt:
    secret: