CREATE TABLE USER_SECRETS
(
    ID INT NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    ROLES JSONB NOT NULL,
    PROVIDER VARCHAR(10) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE CONFIRMATION_TOKEN
(
    ID INT GENERATED ALWAYS AS IDENTITY,
    USER_ID INT NOT NULL,
    CONFIRMATION_TOKEN VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_USER_SECRETS
        FOREIGN KEY (USER_ID)
            REFERENCES USER_SECRETS(ID)
);