CREATE TABLE REFRESH_TOKEN
(
    ID INT GENERATED ALWAYS AS IDENTITY,
    USER_ID INT NOT NULL,
    REFRESH_TOKEN VARCHAR(50) NOT NULL,
    EXPIRY_DATE TIMESTAMP NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_USER_SECRETS
        FOREIGN KEY (USER_ID)
            REFERENCES USER_SECRETS(ID)
);