CREATE TABLE USERS
(
    ID INT GENERATED ALWAYS AS IDENTITY,
    EMAIL VARCHAR(100) NOT NULL,
    FIRSTNAME VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(25) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    ADDRESS JSONB,
    PRIMARY KEY(ID)
);

CREATE TABLE PREFERENCES
(
    USER_ID INT NOT NULL,
    CATEGORIES JSONB,
    SERVICE_LOCATIONS JSONB,
    SELF_DELIVERY_WITHIN_CITY BOOLEAN NOT NULL,
    DELIVERY_SERVICE_REQUIRED BOOLEAN NOT NULL,
    CONSTRAINT FK_USERS
        FOREIGN KEY (USER_ID)
            REFERENCES USERS(ID)
);